server:
  port: 9191

eureka:
  instance:
    hostname: localhost
    non-secure-port: 8761
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}/eureka/

spring:
  application:
    name: recycling-api-gateway 
  cloud:
    gateway:
      
      discovery:
        locator:
          enabled: true
      routes:
        - id: recycling-product.service
          uri: lb://recycling-product.service
          predicates:
            - Path=/api/products/**