server:
  port: 9191

spring:
  application:
    name: recycling-api-gateway 
  cloud:
    gateway:
          
      discovery:
        locator:
          enabled: true
      routes:
        - id: recycling-product.service
          uri: lb://recycling-product.service
          predicates:
            - Path=/api/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: recycling-product.service
                fallbackuri: forward:/productsServiceFallBackMethod
             
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
         thread:
          timeoutInMilliseconds: 4000 
          
management:  endpoints:    web:
      exposure:
        include: hystrix.stream
  
      